return {
    -- 2hr
    ['Inferno'] = 'SPBloodPact',
    ['EarthenFurry'] = 'SPBloodPact',
    ['Tidal Wave'] = 'SPBloodPact',
    ['Aerial Blast'] = 'SPBloodPact',
    ['Clarsach Call'] = 'SPBloodPact',
    ['Diamond Dust'] = 'SPBloodPact',
    ['Judgment Bolt'] = 'SPBloodPact',
    ['Searing Light'] = 'SPBloodPact',
    ['Howling Moon'] = 'SPBloodPact',
    ['Ruinous Omen'] = 'SPBloodPact',

    ['Zantetsuken'] = 'SPBloodPact',

    -- Hybrid
    ['Burning Strike'] = 'HybridBloodPact',
    ['Flaming Crush'] = 'HybridBloodPact',

    -- Breath
    ['Nether Blast'] = 'BreathBloodPact',
    ['Conflag Strike'] = 'BreathBloodPact',

    -- Physical
    ['Punch'] = 'PhysicalBloodPact',
    ['Rock Throw'] = 'PhysicalBloodPact',
    ['Barracuda Dive'] = 'PhysicalBloodPact',
    ['Claw'] = 'PhysicalBloodPact',
    ['Welt'] = 'PhysicalBloodPact',
    ['Axe Kick'] = 'PhysicalBloodPact',
    ['Shock Strike'] = 'PhysicalBloodPact',
    ['Camisado'] = 'PhysicalBloodPact',
    ['Regal Scratch'] = 'PhysicalBloodPact',
    ['Poison Nails'] = 'PhysicalBloodPact',
    ['Moonlit Charge'] = 'PhysicalBloodPact',
    ['Crescent Fang'] = 'PhysicalBloodPact',
    ['Rock Buster'] = 'PhysicalBloodPact',

    ['Roundhouse'] = 'PhysicalBloodPact',
    ['Tail Whip'] = 'PhysicalBloodPact',
    ['Double Punch'] = 'PhysicalBloodPact',
    ['Megalith Throw'] = 'PhysicalBloodPact',
    ['Double Slap'] = 'PhysicalBloodPact',
    ['Meteorite'] = 'PhysicalBloodPact',

    ['Eclipse Bite'] = 'PhysicalBloodPact',


    ['Mountain Buster'] = 'PhysicalBloodPact',
    ['Spinning Dive'] = 'PhysicalBloodPact',
    ['Predator Claws'] = 'PhysicalBloodPact',
    ['Rush'] = 'PhysicalBloodPact',
    ['Chaotic Strike'] = 'PhysicalBloodPact',

    ['Volt Strike'] = 'PhysicalBloodPact',
    ['Hysteric Assault'] = 'PhysicalBloodPact',
    ['Crag Throw'] = 'PhysicalBloodPact',
    ['Blindside'] = 'PhysicalBloodPact',
    ['Regal Gash'] = 'PhysicalBloodPact',
    
    -- Magic
    ['Thunderspark'] = 'MagicBloodPact',
    ['Sonic Buffet'] = 'MagicBloodPact',
    ['Holy Mist'] = 'MagicBloodPact',
    ['Lunar Bay'] = 'MagicBloodPact',
    ['Night Terror'] = 'MagicBloodPact',
    ['Level ? Holy'] = 'MagicBloodPact',
    ['Impact'] = 'MagicBloodPact',
    
    ['Fire II'] = 'MagicBloodPact',
    ['Stone II'] = 'MagicBloodPact',
    ['Water II'] = 'MagicBloodPact',
    ['Aero II'] = 'MagicBloodPact',
    ['Blizzard II'] = 'MagicBloodPact',
    ['Thunder II'] = 'MagicBloodPact',
    ['Fire IV'] = 'MagicBloodPact',
    ['Stone IV'] = 'MagicBloodPact',
    ['Water IV'] = 'MagicBloodPact',
    ['Aero IV'] = 'MagicBloodPact',
    ['Blizzard IV'] = 'MagicBloodPact',
    ['Thunder IV'] = 'MagicBloodPact',
    ['Tornado II'] = 'MagicBloodPact',

    -- Merit BPs
    ['Meteor Strike'] = 'MeritBloodPact',
    ['Geocrush'] = 'MeritBloodPact',
    ['Grand Fall'] = 'MeritBloodPact',
    ['Wind Blade'] = 'MeritBloodPact',
    ['Heavenly Strike'] = 'MeritBloodPact',
    ['Thunderstorm'] = 'MeritBloodPact',

    -- Ward
    ['Altana\'s Favor'] = 'BloodPactWard',
    ['Healing Ruby'] = 'BloodPactWard',
    ['Lunatic Voice'] = 'BloodPactWard',
    ['Somnolence'] = 'BloodPactWard',
    ['Lunar Cry'] = 'BloodPactWard',
    ['Shining Ruby'] = 'BloodPactWard',
    ['Mewing Lullaby'] = 'BloodPactWard',
    ['Aerial Armor'] = 'BloodPactWard',
    ['Frost Armor'] = 'BloodPactWard',
    ['Nightmare'] = 'BloodPactWard',
    ['Rolling Thunder'] = 'BloodPactWard',
    ['Katabatic Blades'] = 'BloodPactWard',
    ['Lunar Roar'] = 'BloodPactWard',
    ['Whispering Wind'] = 'BloodPactWard',
    ['Ultimate Terror'] = 'BloodPactWard',
    ['Crimson Howl'] = 'BloodPactWard',
    ['Lightning Armor'] = 'BloodPactWard',
    ['Chinook'] = 'BloodPactWard',
    ['Ecliptic Growl'] = 'BloodPactWard',
    ['Glittering Ruby'] = 'BloodPactWard',
    ['Earthen Ward'] = 'BloodPactWard',
    ['Spring Water'] = 'BloodPactWard',
    ['Noctoshield'] = 'BloodPactWard',
    ['BitterElegy'] = 'BloodPactWard',
    ['Ecliptic Howl'] = 'BloodPactWard',
    ['Eerie Eye'] = 'BloodPactWard',
    ['Dream Shroud'] = 'BloodPactWard',
    ['Healing Ruby II'] = 'BloodPactWard',
    ['Perfect Defense'] = 'BloodPactWard',
    ['Deconstruction'] = 'BloodPactWard',
    ['Chronoshift'] = 'BloodPactWard',
    ['Earthen Armor'] = 'BloodPactWard',
    ['Tidal Roar'] = 'BloodPactWard',
    ['Fleet Wind'] = 'BloodPactWard',
    ['Inferno Howl'] = 'BloodPactWard',
    ['Wind\'s Blessing'] = 'BloodPactWard',
    ['Diamond Storm'] = 'BloodPactWard',
    ['Shock Squall'] = 'BloodPactWard',
    ['Soothing Ruby'] = 'BloodPactWard',
    ['Heavenward Howl'] = 'BloodPactWard',
    ['Pavor Nocturnus'] = 'BloodPactWard',
    ['Pacifying Ruby'] = 'BloodPactWard',
    ['Soothing Current'] = 'BloodPactWard',
    ['Crystal Blessing'] = 'BloodPactWard',
};
